### ISSUE TITLE
Enabler: App Scaffolding

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/drug-dictionary-app#1]
# Setup App Scaffolding

Setup the app scaffolding as the glossary has.

> **ESTIMATE** 
Duration: 2-3 days

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Sub-Tasks
- [x] Create app scaffold from Playground and update as required
- [x] Set initialize parameters
- [x] Wire up api fetch for drug dictionary

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by amydugan** [comment]
This will be needed to start the first sprint. This will be copied from the playground and modified.
