### ISSUE TITLE
Story: Page Not Found 404

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/drug-dictionary-app#15]
## As a user, if I visit the definition page with a pretty url name that doesn't exist, I should be presented with a page indicating that my link could be bad

> **ESTIMATE** XXX

### Acceptance Criteria

```gherkin
Scenario: Page not found should be displayed when a user visits the definition page with a pretty url that doesn't exist
    Given the user is viewing the definition with the pretty url "chicken"
     Then page title on error page is "Page Not Found"
      And the following links and texts exist on the page: "We can't find the page you're looking for." Visit the homepage, browse by cancer type, or use the search below." "Have a question? Get in touch."
  
      | https://www.cancer.gov         | homepage     | 
      | https://www.cancer.gov/types   | cancer type  | 
      | https://www.cancer.gov/contact | Get in touch | 
  And the search bar appears below the text
```
**Analytics**
```gherkin
Scenario: Page Load Analytics fires for a 404 on the terms page
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
       And "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Publications"
       And "analyticsPublishedDate" is set to "02/02/2011"
       And "analyticsName" is set to "Drug"
    When the user is viewing the definition of "dsadasda"
    Then search results page displays results title "# results found for: M"
    And browser waits
    Then there should be an analytics event with the following details
      | key                                    | value                                                      |
      | type                                   | PageLoad                                                   |
      | event                                  | DrugDictionaryApp:Load:PageNotFound                             |
      | page.name                              | www.cancer.gov/def/dsadasda                                    |
      | page.title                             | Page Not Found                                 |
      | page.metaTitle                         | Page Not Found |
      | page.language                          | english                                                    |
      | page.type                              | nciAppModulePage                                           |
      | page.audience                          | ??                                                   |
      | page.channel                           | Publications                                               |
      | page.contentGroup                      | NCI Drug Dictionary                             |
      | page.publishedDate                     | 02/02/2011                                                 |
      | page.additionalDetails.dictionaryTitle | NCI Drug Dictionary                         |
      | page.additionalDetails.analyticsName   | Drug                                                |
```

### Notes
* So anything outside of the App routes should be handled by Drupal for an actual 404. so that means that a "404" in the app should only happen for:
  1. On the real web site a definition is not actually found.
  2. On react app dev someone asks for a route not within the app.

---
### Resources
* Example webpage: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/chicken

### Tasks
- [ ] Create 404 page
- [ ] Update `ErrorBoundary` component to display 404 page for 404 errors
- [ ] Update unit tests for `ErrorBoundary` and `Definition` components
- [ ] Integration tests
- [ ] Analytics
- [ ] Add Meta Tags

### Technical Notes
- More notes, or technical nuances/direction

**Comment by kate-mashkina** [comment]
PR is merged
