### ISSUE TITLE
Story: Term Page Display

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/drug-dictionary-app#2]
## As a user, I would like to view drug term information, so that I may be more informed about cancer drug related terms.

> **ESTIMATE** XXX

### Acceptance Criteria

```gherkin
Scenario: As a user, I would like to see term information when I am viewing a term page
  Given "dynamicListingPageBase" is set to "https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention"
  When the user is viewing the definition with the url /def/bevacizumab
  Then the page title is "bevacizumab"
    And the Patient Information link to "https://www.cancer.gov/about-cancer/treatment/drugs/bevacizumab" appears on the page
    And the definition text "A recombinant humanized monoclonal antibody directed against the vascular endothelial growth factor (VEGF), a pro-angiogenic cytokine. Bevacizumab binds to VEGF and inhibits VEGF receptor binding, thereby preventing the growth and maintenance of tumor blood vessels. " appears on the page
   And a table of other names, each row being a name type with names appears on the page.
   And the search box and A-Z browse list appears below the table.
```
SEE BRYAN'S COMMENT BELOW FOR MORE INFORMATION

```gherkin
Scenario: negative: As a user, I see the definition of term I am viewing and do not see the Patient Information Link when it is not provided
  Given the user is viewing the definition with the pretty url " f-18-fluorodeoxygalactose"
 Then the page title is " f-18-fluorodeoxygalactose "
Then the link to Patient Information does not appear on the page
 And the definition text " A radioconjugate containing the D-galactose analogue 2-deoxy-2-fluoro-D-glucose (FDGal) labeled with the positron-emitting radioactive isotope fluorine F18, used for imaging upon positron emitting tomography (PET). With cell uptake much higher in tumor cells compared to normal cells, the F18 moiety of fluorodeoxygalactose F-18 can be visualized upon PET imaging and this agent can be used as a tracer for the evaluation of galactose tumor uptake and metabolism. " appears on the page
```
```gherkin
Scenario: As a CDR manager, I would like to be able to find the CDRID of a definition on the definition page so that I can quickly locate the definition within the CDR system.
  Given the user is viewing the definition with the pretty url "bevacizumab"
  Then there should be a "data-cdr-id" attribute on the definition's title element
```
**Metadata ACs**
```gherkin
Scenario: Term page metadata
   Given the user is viewing the definition with the pretty url "bevacizumab"
  Then the title tag should be "NCI Drug Dictionary - National Cancer Institute"
   And the page contains meta tags with the following properties
            | property | content                           |
            | og:title | NCI Drug Dictionary   |
            | og:url   | http://localhost:3000/def/bevacizumab |
            | robots   | noindex                           |
        And there is a canonical link with the href "https://www.cancer.gov/def/bevacizumab"
```

**Analytics ACs**
```gherkin
  Scenario: Page Load Analytics fires when a user visits a term page.
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
      And "baseHost" is set to "http://localhost:3000"
      And "canonicalHost" is set to "https://www.cancer.gov"
      And "siteName" is set to "National Cancer Institute"
      And "channel" is set to "Publications"
      And "analyticsPublishedDate" is set to "02/02/2011"
      And "analyticsName" is set to "Drug"
     When the user is viewing the definition with the pretty url "bevacizumab"
      And the page title is "bevacizumab"
      And browser waits
     Then there should be an analytics event with the following details
      | key                                    | value                                                                       | 
      | type                                   | PageLoad                                                                    | 
      | event                                  | DrugDictionaryApp:Load:Definition                                           | 
      | page.name                              | www.cancer.gov/def/bevacizumab                                              | 
      | page.title                             | bevacizumab                                                                 | 
      | page.metaTitle                         | Definition of bevacizumab - NCI Drug Dictionary - National Cancer Institute | 
      | page.language                          | english                                                                     | 
      | page.type                              | nciAppModulePage                                                            | 
      | page.audience                          | ???                                                                         | 
      | page.channel                           | Publications                                                                | 
      | page.contentGroup                      | NCI Drug Dictionary                                                         | 
      | page.publishedDate                     | 02/02/2011                                                                  | 
      | page.additionalDetails.dictionaryTitle | NCI Drug Dictionary                                                         | 
      | page.additionalDetails.analyticsName   | Drug                                                                        | 
      | page.additionalDetails.term            | bevacizumab                                                                 | 
      | page.additionalDetails.id              | (int) 415570                                                                | 
```

### Resources:
* Comp: https://publicis.invisionapp.com/share/QDYHYSLCBZY#/screens/429245338
* Web Page: https://www.cancer.gov/publications/dictionaries/cancer-drug/def/bevacizumab

### Notes
* "View Patient Information" button/link appears when a term has a DrugInfoSummaryLink element populated

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [x] Create Definition route and component
- [x] Add `SearchBox` component (# Task)
- [x] Create Synonym table component (# Task)
- [ ] Create `Term` component that would contain "Term Title" and "Term Description" (# Task)
- [x] Fetch term definition from the API ( # Task )
- [ ] Unit tests 
- [ ] Integration test

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
## Table Display Notes
The order and labels for the alias (`term.aliases.type` API property) table are as follow:
* `Synonym` - Synonym
* `USBrandName` - US brand name
* `ForeignBrandName` - Foreign brand name
* `Abbreviation` - Abbreviation
* `Acronym` - Acronym
* `CodeName` - Code name
* `ChemicalStructureName` - Chemical structure
* `INDCode` - IND number
* `NSCNumber` - NSC code

**Comment by arcepaul** [comment]
There should be a story for table display component (including Bryan's comment).  Completion of this story should allow for table placeholder until finished.

**Comment by amydugan** [comment]
Volker, Bob can assist with finding definitions (IND Code, NSC Number).

**Comment by amydugan** [comment]
Need to add ACs for table accessibility (508).

**Comment by bryanpizzillo** [comment]
Pulling the ACs for Clinical Trials links and the NCI Thesaurus.

*    And an active clinical trials link to "https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/C2039" appears after the definition text
*    And an NCI Thesaurus link to "https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039" EVS appears after the clinical trials link

**Comment by amydugan** [comment]
Closed by PR https://github.com/NCIOCPL/drug-dictionary-app/pull/24
