### ISSUE TITLE
Story: Implement basic integration tests 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/drug-dictionary-app#23]
## As a developer, I want implement integration tests, so that we can assure the quality of our Alexa skill.

> **ESTIMATE** XX

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Use nock to implement integration tests
- [ ] Document how integration tests will be automated (consult with QA as needed)

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
accidentally created in wrong repo
