### ISSUE TITLE
Story: View Terms by Letter (/expand)

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/drug-dictionary-app#4]
## As a user, I would like the option to view and browse the dictionary terms using an A-Z list and view the results from selecting a letter so that I can look at the list of terms the dictionary offers.

> **ESTIMATE** Without Testing: 3, With Testing: 5

### Acceptance Criteria

```gherkin
Scenario: User appends /expand to the URL and tries to access the dictionary
    Given user appends "/expand" to the URL
    When user tries to go to this URL, system should return the "No Matches Found" page
```

```gherkin
Scenario: User selects a letter from A-Z list on dictionaries for terms in lists
    Given user is on the dictionary landing page or results page
    When user selects letter "A" from A-Z list
    Then the system returns user to the search results page for the search term "A" URL has "/expand"
    Then search results page displays results title "# results found for: A"
    And each result in the results listing appears as a link to the term's page
    And each result that is an other name that is displayed in results is displayed with its Other Name, with (Other name for: [preferred name]) as its display
    And each result displays its full definition below the link for the term
```

```gherkin
  Scenario: User clicks on a letter in the A-Z list for results and gets no matches found for the selected letter
    <there is no real life situation for these letters, but if a letter had no matches found) 
    Then search results page displays No matches "No matches were found for your selected letter. Please try a new search, or click a different letter in the alphabet and browse through the list of terms that begin with that letter."
```

**Metadata**
```gherkin
Scenario: Results /expand page metadata
    Given the user is viewing a results page based on clicking a letter like "A" in the dictionary
    Then the title tag should be “NCI Drug Dictionary - National Cancer Institute”
    And the page contains meta tags with the following properties
           | property | content                       |
           | og:title | NCI Drug Dictionary          |
           | og:url  | http://localhost:3000/expand/A        |
           | robots  | noindex                         |
       And there is a canonical link with the href "https://www.cancer.gov/expand/A" 
```

**Analytics**
```gherkin
  Scenario: Page Load Analytics fires when a user views an expand result page
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
       And "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Publications"
       And "analyticsPublishedDate" is set to "02/02/2011"
       And "analyticsName" is set to "Drug"
    When the user is viewing a results page based on clicking a letter like "M" in the dictionary
    Then search results page displays results title "# results found for: M"
    And browser waits
    Then there should be an analytics event with the following details
      | key                                    | value                                                      |
      | type                                   | PageLoad                                                   |
      | event                                  | DrugDictionaryApp:Load:ExpandResults                             |
      | page.name                              | www.cancer.gov/expand/M                                    |
      | page.title                             | NCI Drug Dictionary                                 |
      | page.metaTitle                         | NCI Drug Dictionary - National Cancer Institute |
      | page.language                          | english                                                    |
      | page.type                              | nciAppModulePage                                           |
      | page.channel                           | Publications                                               |
      | page.contentGroup                      | NCI Drug Dictionary                             |
      | page.publishedDate                     | 02/02/2011                                                 |
      | page.additionalDetails.dictionaryTitle | NCI Drug Dictionary                             |
      | page.additionalDetails.analyticsName   | Drug                                                |
      | page.additionalDetails.letter          | M                                                         |
      | page.additionalDetails.numberResults   | (int)Find it from the results                                                   |
```

```gherkin
Scenario: User Clicks on an Expand Listing Item (i.e. a result)
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
       And "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Publications"
       And "analyticsPublishedDate" is set to "02/02/2011"
       And "analyticsName" is set to "Drug"
       And the user is viewing a results page based on clicking a letter like "M" in the dictionary
       And search results page displays results title "# results found for: M"
       And browser waits
    When the user clicks on the result for "macimorelin"
    Then there should be an analytics event with the following details
			| key                    | value                          |
			| type                   | Other                          |
			| event                  | DrugDictionaryApp:Other:ResultClick  |
			| linkName               | DrugDictionaryResults				  |
			| data.dictionaryTitle   | NCI Drug Dictionary |
			| data.analyticsName     | Drug                    |
			| data.resultIndex 	     | (int)4 		|
			| data.resultIdOrName	   | macimorelin |
			| data.resultName 		 	 | macimorelin |
```

```gherkin
# Stale, as data below in dev has a prettyUrlName 
#	Scenario: User Clicks on an Expand Listing Item without a prettyurl name (i.e. a result)
#		Given "dictionaryTitle" is set to "NCI Drug Dictionary"
#		And "baseHost" is set to "http://localhost:3000"
#		And "canonicalHost" is set to "https://www.cancer.gov"
#		And "siteName" is set to "National Cancer Institute"
#		And "channel" is set to "Publications"
#		And "analyticsPublishedDate" is set to "02/02/2011"
#		And "analyticsName" is set to "Drug"
#		And the user is viewing a results page based on clicking a letter like "M" in the dictionary
#		And search results page displays results title "# results found for: M"
#		And browser waits
#		When the user clicks on the result for "macrocycle-bridged STING agonist E7766"
#		Then there should be an analytics event with the following details
#			| key                  | value                                  |
#			| type                 | Other                                  |
#			| event                | DrugDictionaryApp:Other:ResultClick    |
#			| linkName             | DrugDictionaryResults                  |
#			| data.dictionaryTitle | NCI Drug Dictionary                    |
#			| data.analyticsName   | Drug                                   |
#			| data.resultIndex     | (int)6                                 |
#			| data.resultIdOrName  | (int)799924                            |
#			| data.resultName      | macrocycle-bridged STING agonist E7766 | 

  Scenario: User Clicks on an Expand Listing Item without a prettyurl name (i.e. a result)
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
      And "baseHost" is set to "http://localhost:3000"
      And "canonicalHost" is set to "https://www.cancer.gov"
      And "siteName" is set to "National Cancer Institute"
      And "channel" is set to "Publications"
      And "analyticsPublishedDate" is set to "02/02/2011"
      And "analyticsName" is set to "Drug"
      And the user is viewing a results page based on clicking a letter like "E" in the dictionary
      And search results page displays results title "# results found for: E"
     When the user clicks on the result for "expanded cord blood stem cells mixed with engineered human endothelial cells AB-110"
     Then there should be an analytics event with the following details
      | key                  | value                                                                               | 
      | type                 | Other                                                                               | 
      | event                | DrugDictionaryApp:Other:ResultClick                                                 | 
      | linkName             | DrugDictionaryResults                                                               | 
      | data.dictionaryTitle | NCI Drug Dictionary                                                                 | 
      | data.analyticsName   | Drug                                                                                | 
      | data.resultIndex     | (int)208                                                                            | 
      | data.resultIdOrName  | (int)795426                                                                         | 
      | data.resultName      | expanded cord blood stem cells mixed with engineered human endothelial cells AB-110 | 

```

### Resources:
* Web Page:* https://www.cancer.gov/publications/dictionaries/cancer-drug?expand=D

---

### Task list
- [ ] Add `SearchBox` component to home page
- [ ] Create results display page ( List & Item ) as `TermList` component
- [ ] Fetch requested expand results from API
- [ ] Ensure that "robots:noindex" is added to the /expand URLs
- [ ] Build results page for "No Terms matching Letter selected" message 
- [ ] Write automated tests

### Technical Notes
- Wanted to draw attention to the fact that both Preferred Names and Other Names show in the alphabetical listing for the results, as described in the ACs.  Example: Avastin will display as Avastin Other name for: bevacizumab) (https://www.cancer.gov/publications/dictionaries/cancer-drug?expand=A&first=801&page=8)

**Comment by bryanpizzillo** [comment]
This was closed by PR #36
