### ISSUE TITLE
Story: Keyword Search (/search URL)

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/drug-dictionary-app#5]
## As a user, I would like to be able to enter keywords and have the option to submit a search

> **ESTIMATE** With bold, with tests: 5, Without bold: 3, Without tests: 3

### Acceptance Criteria

```gherkin
Scenario: User enters /search in the URL and tries to access the dictionary
Given user has entered /publications/dictionaries/cancer-drug/search in the URL
  When user tries to go to this URL, system should return the "No Matches Found" page
```
```gherkin
Scenario: User is able to enter keywords for a search
Given user is on the drug dictionary landing page 
  Then search bar is displayed below introductory text 
    And search bar contains a placeholder text “Enter keywords or phrases” 
    And “Search” button is displayed 
  When user starts typing in the search bar 
  Then placeholder text disappears  
  And user is able to click "Search" to submit their search
  Then the system returns search results page for the search term (URL has /search)
  And the page displays the following label above the results: “# results found for: <word or phrase>"
    And each result in the results listing displays the preferred name as a link to the term’s page 
    And the preferred name is followed by the alternate names that matched the text on the same line
    And each result displays its full definition below the link for the term 
```

```gherkin
Scenario: User executes a "starts with" search after entering terms using preferred name.
  Given user is on landing page for Drug Dictionary (/ URL) 
  Then “Starts with” and “Contains” options are displayed 
    And “Starts with” is selected by default 
  When user starts typing "<keyword>" in the search bar 
    And user clicks on Search button 
  Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /search)
    And page displays "# results found for:" "<keyword>"  
    And List of results is displayed 
    And result <resultNumber> displays as "<linkedResult>" with "<alternateName>"
    And “Starts with” is selected by default 
    And search bar contains the "<keyword>" that user entered  

Examples:
|keyword|resultNumber|linkedResult|alternateName|
|bevacizumab|1|none|none|
|[18F]f|1|none|none|
|3'-|4|dichloromethotrexate | 3'-5'-dichloromethotrexate|
|5%|1|none|none|
|bin|1|alendronate sodium|Binosto|
|amino|8|aminolevulinic acid hydrochloride|aminolevulinic acid HCl; amino-levulinic acid hydrochloride; amino-levulinic acid hydrochloride|

```

```gherkin
Scenario: User executes a "contains" search after entering terms.
  Given user is on Drug Dictionary Landing Page (/ URL)
  Then “Starts with” and “Contains” options are displayed 
    And “Starts with” is selected by default 
  Then user selects Contains option
  Then user starts typing "<keyword>" in the search bar 
    And user clicks on Search button 
  Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /search)
    And page displays "# results found for:" "<keyword>"
    And List of results is displayed
    And result <resultNumber> displays as "<linkedResult>" with "<alternateName>"
    And “Contains” remains selected 
    And search bar contains the word "<keyword>" that user entered  

Examples
|keyword|resultNumber|linkedResult|alternateName|
|Avastin|1|bevacizumab|Avastin|
|/cd40|1|none|none|
|1/3|2|ethinyl estradiol/norethindrone|Ortho-Novum 1/35|
|-4'|6| niclosamide |salicylanilide, 2',5-dichloro-4'-nitro-|
|5%|1|none|none|


```

```gherkin
Scenario: User enters a keyword or phrase that does not generate any matches
 Given user is on Drug Dictionary landing page (/ URL)
 When user enters "chicken pot pie" in the keyword box
 Then Search is executed  
    Then the page displays the no matches found page: “No matches were found for the word or phrase you entered. Please check your spelling, and try searching again. You can also type the first few letters of your word or phrase, or click a letter in the alphabet and browse through the list of terms that begin with that letter."
```

```gherkin
Scenario: Search page metadata
 Given user is searching "startsWith" for the term "Avastin"
  Then the title tag should be "NCI Drug Dictionary - National Cancer Institute"
   And the page contains meta tags with the following properties
            | property | content                           |
            | og:title | NCI Drug Dictionary   |
            | og:url   | http://localhost:3000/search/avastin |
            | robots   | noindex                           |
        And there is a canonical link with the href "https://www.cancer.gov/search/avastin"  
```   

**Analytics**
```gherkin
  Scenario: Page Load Analytics fires when a user views a "starts with" search result page
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
       And "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Publications"
       And "analyticsPublishedDate" is set to "02/02/2011"
       And "analyticsName" is set to "Drug"
    When user is searching "startsWith" for the term "beva"
      And search results page displays results title "# results found for: " "beva"
      And browser waits
    Then there should be an analytics event with the following details
      | key                                    | value                                                      |
      | type                                   | PageLoad                                                   |
      | event                                  | DrugDictionaryApp:Load:SearchResults                             |
      | page.name                              | www.cancer.gov/search/beva                                 |
      | page.title                             | NCI Drug Dictionary                                  |
      | page.metaTitle                         | NCI Drug Dictionary - National Cancer Institute |
      | page.language                          | english                                                    |
      | page.type                              | nciAppModulePage                                           |
      | page.audience                          | ??                                                    |
      | page.channel                           | Publications                                               |
      | page.contentGroup                      | NCI Drug Dictionary                             |
      | page.publishedDate                     | 02/02/2011                                                 |
      | page.additionalDetails.numberResults   | (int)FIND THE NUMBER                                                    |
      | page.additionalDetails.searchKeyword   | beva                                                       |
      | page.additionalDetails.searchType      | StartsWith                                                 |
      | page.additionalDetails.analyticsName   | Drug                                                |
      | page.additionalDetails.dictionaryTitle | NCI Drug Dictionary                            |
```

```gherkin
  Scenario: Page Load Analytics fires when a user views a "contains" search result page
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "siteName" is set to "National Cancer Institute"
    And "channel" is set to "Publications"
    And "analyticsPublishedDate" is set to "02/02/2011"
    And "analyticsName" is set to "Drug"
    When user is searching "contains" for the term "beva"
      And search results page displays results title "# results found for: " "beva"
      And browser waits
    Then there should be an analytics event with the following details
      | key                                    | value                                                      |
      | type                                   | PageLoad                                                   |
      | event                                  | DrugDictionaryApp:Load:SearchResults                             |
      | page.name                              | www.cancer.gov/search/beva                                 |
      | page.title                             | NCI Drug Dictionary                                  |
      | page.metaTitle                         | NCI Drug Dictionary - National Cancer Institute |
      | page.language                          | english                                                    |
      | page.type                              | nciAppModulePage                                           |
      | page.audience                          | ??                                                    |
      | page.channel                           | Publications                                               |
      | page.contentGroup                      | NCI Drug Dictionary                             |
      | page.publishedDate                     | 02/02/2011                                                 |
      | page.additionalDetails.numberResults   | (int)FIND THE NUMBER                                                    |
      | page.additionalDetails.searchKeyword   | beva                                                       |
      | page.additionalDetails.searchType      | Contains                                                   |
      | page.additionalDetails.analyticsName   | Drug                                                |
      | page.additionalDetails.dictionaryTitle | NCI Drug Dictionary                            |
```

```gherkin
Scenario: User Clicks on a search result
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
       And "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Publications"
       And "analyticsPublishedDate" is set to "02/02/2011"
       And "analyticsName" is set to "Drug"
      And user is searching "startsWith" for the term "macro"
      And search results page displays results title "# results found for: " "macro"
      And browser waits
    When the user clicks on the result for "macrogol 3350-based oral osmotic laxative"
    Then there should be an analytics event with the following details
			| key                    | value                          |
			| type                   | Other                          |
			| event                  | DrugDictionaryApp:Other:ResultClick  |
			| linkName               | DrugDictionaryResults				  |
			| data.dictionaryTitle   | NCI Drug Dictionary |
			| data.analyticsName     | Drug                    |
			| data.resultIndex 	     | (int)1 		|
			| data.resultIdOrName	   | macrogol-3350-based-oral-osmotic-laxative |
			| data.resultName 		 	 | macrogol 3350-based oral osmotic laxative |
```

```gherkin
Scenario: User Clicks on a search result
    Given "dictionaryTitle" is set to "NCI Drug Dictionary"
       And "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Publications"
       And "analyticsPublishedDate" is set to "02/02/2011"
       And "analyticsName" is set to "Drug"
      And user is searching "startsWith" for the term "macro"
      And search results page displays results title "# results found for: " "macro"
      And browser waits
    When the user clicks on the result for "macrocycle-bridged STING agonist E7766"
    Then there should be an analytics event with the following details
			| key                    | value                          |
			| type                   | Other                          |
			| event                  | DrugDictionaryApp:Other:ResultClick  |
			| linkName               | DrugDictionaryResults				  |
			| data.dictionaryTitle   | NCI Drug Dictionary |
			| data.analyticsName     | Drug                    |
			| data.resultIndex 	     | (int)1 		|
			| data.resultIdOrName	   | (int)799924 |
			| data.resultName 		 	 | macrocycle-bridged STING agonist E7766 |
```

### Resources:
* Feature: https://tracker.nci.nih.gov/browse/CGOVWCMS-30

### Notes

---

### Tasks
- [x] Create basic search page with Search Box, "Starts with" button, "Contains" button, and clickable A-Z list
- [x] Create display for results list item 
- [x] Create results list view
- [x] Fetch result from API
- [x] Ensure that "robots:noindex" is added to the /search and /buscar URLs
- [x] Build results page for "No Terms matching search" message 
- [x] Write automated tests

### Technical Notes
- More notes, or technical nuances/direction
 - If the preferred name has a part that matches searched keyword it will bold that part out for the first occurrence only. Beginning for a "Starts with" search and within the word for a 'Contains" search. 
 - the alternative names in the square brackets will display only synonyms that have partial match of the searched keyword at the beginning of each word for a "Starts with" search and within each word for a "Contains" search (if more than one, separated by ; )

#### Screenshot for a "Starts with" search using "ac" as the search keyword 
(note: "Check for active clinical trials using this agent. (NCI Thesaurus)" should not display on the search results page)
<img width="864" alt="Screen Shot 2020-08-25 at 1 56 40 PM" src="https://user-images.githubusercontent.com/58226882/91211548-f375d200-e6dc-11ea-971d-7d126bd5a8c9.png">

#### Screenshot for a "Contains" search using "ac" as the search keyword 
(note: "Check for active clinical trials using this agent. (NCI Thesaurus)" should not display on the search results page)
<img width="869" alt="Screen Shot 2020-08-25 at 1 57 54 PM" src="https://user-images.githubusercontent.com/58226882/91211557-f7a1ef80-e6dc-11ea-8a02-6b4d89bceec9.png">

<img width="750" alt="Screen Shot 2020-08-21 at 12 36 39 PM" src="https://user-images.githubusercontent.com/67657582/90914363-cb6c3300-e3ab-11ea-9ceb-3d19088f644e.png">

**Comment by mworrest** [comment]
Style updates for search and expand: bold the full term. Unbold synonyms and put them underneath term with label "Matching synonym" in bold. This is singular even if there's multiple synonyms just like we see in the table on the definition page.
![drug-dictionary-comp](https://user-images.githubusercontent.com/4921685/96269776-cd600600-0f98-11eb-8cc8-00ee02eda2e9.jpg)
